# Generated by Django 4.1.7 on 2023-03-15 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('length', models.FloatField()),
                ('height', models.FloatField()),
                ('gender', models.CharField(choices=[('m', 'MALE'), ('f', 'FEMALE'), ('o', 'OTHER')], help_text='Пол', max_length=1)),
                ('lifeStatus', models.CharField(choices=[('a', 'ALIVE'), ('d', 'DEAD')], default='a', help_text='Жизненный статус', max_length=1)),
                ('chippingDateTime', models.DateTimeField(auto_now=True)),
                ('deathDateTime', models.DateTimeField(null=True)),
                ('animalTypes', models.ManyToManyField(to='animal.type')),
                ('chipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('chippingLocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chipping_location', to='location.location')),
                ('visitedLocations', models.ManyToManyField(related_name='visited_location', to='location.location')),
            ],
        ),
    ]
